### ISSUE TITLE
Collate import incompatible with torch version <1.13

### ISSUE THREAD

**Issue by tryptofanik** [chython/chytorch#5]
One import makes chytorch incompatible with PyTorch with a version smaller than 1.13. 

The import is located in `utils/data/molecule/contrastive.py` (line 25):
```
from torch.utils.data._utils.collate import default_collate_fn_map
```
In torch 1.13 dict `default_collate_fn_map` can be found here: https://github.com/pytorch/pytorch/blob/v1.13.0/torch/utils/data/_utils/collate.py#L191 , however in older versions it is not present.

It seems that it is enough to copy-paste the code from PyTorch 1.13 that is responsible for creating `default_collate_fn_map`:

```
default_collate_fn_map: Dict[Union[Type, Tuple[Type, ...]], Callable] = {torch.Tensor: collate_tensor_fn}
with contextlib.suppress(ImportError):
    import numpy as np
    # For both ndarray and memmap (subclass of ndarray)
    default_collate_fn_map[np.ndarray] = collate_numpy_array_fn
    # See scalars hierarchy: https://numpy.org/doc/stable/reference/arrays.scalars.html
    # Skip string scalars
    default_collate_fn_map[(np.bool_, np.number, np.object_)] = collate_numpy_scalar_fn
default_collate_fn_map[float] = collate_float_fn
default_collate_fn_map[int] = collate_int_fn
default_collate_fn_map[string_classes] = collate_str_fn
```

Although I do not see any usage of the `default_collate_fn_map` in the repo... Is it relevant to have it?

**Comment by tryptofanik** [comment]
Actually, I think that it is neccessary to fix also other occurrences of `default_collate_fn_map`: 

![image](https://user-images.githubusercontent.com/49122854/208871040-126b6d72-14d8-4d64-8ca2-83f67e5e52a3.png)

**Comment by stsouko** [comment]
fixed
